exclude_patterns:
  - ".github/"
  - ".idea/"
  - "stubs/"
  - "*.stub"
  - "tests/"
  - "**/vendor/"
  - "**/node_modules/"
  - "*.md"
  - ".*.yml"
  - "LICENSE"
  - "composer.json"
  - "phpunit.xml"
