name: CI PHPStan

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
            php_version: "8.4"

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: src/
          php_version: "8.4"
